/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: string;
  cta?: Cta;
  tone?: "info" | "success" | "warning";
  isActive?: boolean;
  link?: string;
  linkText?: string;
  backgroundColor?: string;
};

export type Cta = {
  _type: "cta";
  label?: string;
  url?: string;
  style?: "primary" | "secondary" | "link";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PartnerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "partner";
};

export type LabsProject = {
  _id: string;
  _type: "labsProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: PortableText;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tags?: Array<string>;
  partnerRef?: PartnerReference;
  partner?: string;
  status?: "upcoming" | "active" | "completed";
  displayOrder?: number;
  startDate?: string;
  endDate?: string;
  publicationUrl?: string;
  cta?: Cta;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  url?: string;
  category?: "research" | "ecosystem" | "investor" | "integration";
  isPublic?: boolean;
  displayOrder?: number;
  internalNote?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "externalLink";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
  | ({
      _key: string;
    } & Code)
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: PortableText;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  isFeatured?: boolean;
  readingTime?: number;
  seo?: Seo;
  seoTitle?: string;
  seoDescription?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  role?: string;
  bio?: string;
  linkedin?: string;
  twitter?: string;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  url?: string;
  openInNewTab?: boolean;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Announcement
  | Cta
  | SanityImageAssetReference
  | PartnerReference
  | LabsProject
  | Seo
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | PortableText
  | Slug
  | Category
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | ImageWithAlt
  | Link
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(publishedAt desc, _id asc) {  _id, _type, title, "slug": slug.current, excerpt, publishedAt, isFeatured, readingTime,  "category": categories[0]->title,  "author": author->{name, "avatar": avatar.asset->url},  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  category: string | null;
  author: {
    name: string | null;
    avatar: string | null;
  } | null;
  coverImage: string | null;
  coverImageAlt: string | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: FEATURED_POST_QUERY
// Query: *[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(isFeatured desc, publishedAt desc, _id asc)[0] {  _id, _type, title, "slug": slug.current, excerpt, publishedAt, readingTime,  "category": categories[0]->title,  "author": author->{name, "avatar": avatar.asset->url},  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt}
export type FEATURED_POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  readingTime: number | null;
  category: string | null;
  author: {
    name: string | null;
    avatar: string | null;
  } | null;
  coverImage: string | null;
  coverImageAlt: string | null;
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: PAGINATED_POSTS_QUERY
// Query: *[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && _id != $featuredId] | order(publishedAt desc, _id asc) [$start...$end] {  _id, _type, title, "slug": slug.current, excerpt, publishedAt, readingTime,  "category": categories[0]->title,  "author": author->{name, "avatar": avatar.asset->url},  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt}
export type PAGINATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  readingTime: number | null;
  category: string | null;
  author: {
    name: string | null;
    avatar: string | null;
  } | null;
  coverImage: string | null;
  coverImageAlt: string | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: NON_FEATURED_COUNT_QUERY
// Query: count(*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && _id != $featuredId])
export type NON_FEATURED_COUNT_QUERY_RESULT = number;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && defined(publishedAt) && slug.current == $slug && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(_updatedAt desc)[0] {  _id, _type, title, "slug": slug.current, excerpt, publishedAt, readingTime,  body[]{..., _type == "imageWithAlt" => {..., "url": asset->url}},  "seoTitle": coalesce(seo.title, seoTitle, title),  "seoDescription": coalesce(seo.description, seoDescription, excerpt),  "category": categories[0]->title, "categories": categories[]->title,  "author": author->{name, role, bio, "avatar": avatar.asset->url, linkedin, twitter},  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt}
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  readingTime: number | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "externalLink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        url: string | null;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  category: string | null;
  categories: Array<string | null> | null;
  author: {
    name: string | null;
    role: string | null;
    bio: string | null;
    avatar: string | null;
    linkedin: string | null;
    twitter: string | null;
  } | null;
  coverImage: string | null;
  coverImageAlt: string | null;
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: LABS_PROJECTS_QUERY
// Query: *[_type == "labsProject" && ($preview || !(_id in path("drafts.**")))] | order(coalesce(displayOrder, 100) asc, startDate desc, _id asc) {  _id, _type, title, "slug": slug.current, status, "partner": coalesce(partnerRef->name, partner),  description, body[]{..., _type == "imageWithAlt" => {..., "url": asset->url}}, tags,  startDate, endDate, publicationUrl, cta,  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt}
export type LABS_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "labsProject";
  title: string | null;
  slug: string | null;
  status: "active" | "completed" | "upcoming" | null;
  partner: string | null;
  description: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "externalLink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        url: string | null;
      }
  > | null;
  tags: Array<string> | null;
  startDate: string | null;
  endDate: string | null;
  publicationUrl: string | null;
  cta: Cta | null;
  coverImage: string | null;
  coverImageAlt: string | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: ACTIVE_ANNOUNCEMENT_QUERY
// Query: *[_type == "announcement" && isActive == true && ($preview || !(_id in path("drafts.**")))] | order(_updatedAt desc, _id asc)[0] {  _id, _type, text, tone,  "cta": coalesce(cta, {"label": linkText, "url": link})}
export type ACTIVE_ANNOUNCEMENT_QUERY_RESULT = {
  _id: string;
  _type: "announcement";
  text: string | null;
  tone: "info" | "success" | "warning" | null;
  cta:
    | Cta
    | {
        label: string | null;
        url: string | null;
      };
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(publishedAt desc, _id asc) {\n  _id, _type, title, "slug": slug.current, excerpt, publishedAt, isFeatured, readingTime,\n  "category": categories[0]->title,\n  "author": author->{name, "avatar": avatar.asset->url},\n  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt\n}': POSTS_QUERY_RESULT;
    '*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(isFeatured desc, publishedAt desc, _id asc)[0] {\n  _id, _type, title, "slug": slug.current, excerpt, publishedAt, readingTime,\n  "category": categories[0]->title,\n  "author": author->{name, "avatar": avatar.asset->url},\n  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt\n}': FEATURED_POST_QUERY_RESULT;
    '*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && _id != $featuredId] | order(publishedAt desc, _id asc) [$start...$end] {\n  _id, _type, title, "slug": slug.current, excerpt, publishedAt, readingTime,\n  "category": categories[0]->title,\n  "author": author->{name, "avatar": avatar.asset->url},\n  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt\n}': PAGINATED_POSTS_QUERY_RESULT;
    'count(*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && _id != $featuredId])': NON_FEATURED_COUNT_QUERY_RESULT;
    '*[_type == "post" && defined(publishedAt) && slug.current == $slug && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(_updatedAt desc)[0] {\n  _id, _type, title, "slug": slug.current, excerpt, publishedAt, readingTime,\n  body[]{..., _type == "imageWithAlt" => {..., "url": asset->url}},\n  "seoTitle": coalesce(seo.title, seoTitle, title),\n  "seoDescription": coalesce(seo.description, seoDescription, excerpt),\n  "category": categories[0]->title, "categories": categories[]->title,\n  "author": author->{name, role, bio, "avatar": avatar.asset->url, linkedin, twitter},\n  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt\n}': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "labsProject" && ($preview || !(_id in path("drafts.**")))] | order(coalesce(displayOrder, 100) asc, startDate desc, _id asc) {\n  _id, _type, title, "slug": slug.current, status, "partner": coalesce(partnerRef->name, partner),\n  description, body[]{..., _type == "imageWithAlt" => {..., "url": asset->url}}, tags,\n  startDate, endDate, publicationUrl, cta,\n  "coverImage": coverImage.asset->url, "coverImageAlt": coverImage.alt\n}': LABS_PROJECTS_QUERY_RESULT;
    '*[_type == "announcement" && isActive == true && ($preview || !(_id in path("drafts.**")))] | order(_updatedAt desc, _id asc)[0] {\n  _id, _type, text, tone,\n  "cta": coalesce(cta, {"label": linkText, "url": link})\n}': ACTIVE_ANNOUNCEMENT_QUERY_RESULT;
  }
}
