/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: string;
  cta?: Cta;
  tone?: "info" | "success" | "warning";
  isActive?: boolean;
  link?: string;
  linkText?: string;
  backgroundColor?: string;
};

export type Cta = {
  _type: "cta";
  label?: string;
  url?: string;
  style?: "primary" | "secondary" | "link";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PartnerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "partner";
};

export type LabsProject = {
  _id: string;
  _type: "labsProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: PortableText;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tags?: Array<string>;
  partnerRef?: PartnerReference;
  partner?: string;
  status?: "upcoming" | "active" | "completed";
  displayOrder?: number;
  startDate?: string;
  endDate?: string;
  publicationUrl?: string;
  cta?: Cta;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  url?: string;
  category?: "research" | "ecosystem" | "investor" | "integration";
  isPublic?: boolean;
  displayOrder?: number;
  internalNote?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "externalLink";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
  | ({
      _key: string;
    } & Code)
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: PortableText;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  isFeatured?: boolean;
  readingTime?: number;
  seo?: Seo;
  seoTitle?: string;
  seoDescription?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  role?: string;
  bio?: string;
  linkedin?: string;
  twitter?: string;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  url?: string;
  openInNewTab?: boolean;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Announcement
  | Cta
  | SanityImageAssetReference
  | PartnerReference
  | LabsProject
  | Seo
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | PortableText
  | Slug
  | Category
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | ImageWithAlt
  | Link
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(publishedAt desc, _id asc) {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  isFeatured, readingTime,  "category": categories[0]->{_id, title, "slug": slug.current},  "categories": categories[]->{_id, title, "slug": slug.current},  "author": author->{_id, name, "slug": slug.current, role, avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: BLOG_CATEGORIES_QUERY
// Query: *[  _type == "category" && ($preview || !(_id in path("drafts.**"))) &&  count(*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && references(^._id)]) > 0] | order(title asc, _id asc) {  _id, title, "slug": slug.current}
export type BLOG_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: BLOG_TOTAL_COUNT_QUERY
// Query: count(*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))])
export type BLOG_TOTAL_COUNT_QUERY_RESULT = number;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: ANNOUNCEMENT_STORY_QUERY
// Query: *[  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && "announcements" in categories[]->slug.current] | order(publishedAt desc, _id asc)[0] {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  isFeatured, readingTime,  "category": categories[0]->{_id, title, "slug": slug.current},  "categories": categories[]->{_id, title, "slug": slug.current},  "author": author->{_id, name, "slug": slug.current, role, avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type ANNOUNCEMENT_STORY_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: FEATURED_POST_QUERY
// Query: *[  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && isFeatured == true] | order(publishedAt desc, _id asc)[0] {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  isFeatured, readingTime,  "category": categories[0]->{_id, title, "slug": slug.current},  "categories": categories[]->{_id, title, "slug": slug.current},  "author": author->{_id, name, "slug": slug.current, role, avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type FEATURED_POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && !(_id in $excludeIds) &&  ($category == "" || $category in categories[]->slug.current) &&  ($search == "" || lower(title) match $search || lower(excerpt) match $search)] | order(publishedAt desc, _id asc) [$start...$end] {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  isFeatured, readingTime,  "category": categories[0]->{_id, title, "slug": slug.current},  "categories": categories[]->{_id, title, "slug": slug.current},  "author": author->{_id, name, "slug": slug.current, role, avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: BLOG_POST_COUNT_QUERY
// Query: count(*[  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && !(_id in $excludeIds) &&  ($category == "" || $category in categories[]->slug.current) &&  ($search == "" || lower(title) match $search || lower(excerpt) match $search)])
export type BLOG_POST_COUNT_QUERY_RESULT = number;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[  _type == "post" && slug.current == $slug && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(_updatedAt desc)[0] {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  isFeatured, readingTime,  body[]{..., _type == "imageWithAlt" => {..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  "seo": {    "title": coalesce(seo.title, seoTitle, title),    "description": coalesce(seo.description, seoDescription, excerpt),    "noIndex": coalesce(seo.noIndex, false),    "image": seo.image{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}  },  "category": categories[0]->{_id, title, "slug": slug.current},  "categories": categories[]->{_id, title, "slug": slug.current},  "author": author->{    _id, name, "slug": slug.current, role, bio, linkedin, twitter,    avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}  },  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "externalLink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
              lqip: null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | false;
    image: {
      _type: "imageWithAlt";
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
    } | null;
  };
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    twitter: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: AUTHOR_BY_SLUG_QUERY
// Query: *[  _type == "author" && slug.current == $slug && ($preview || !(_id in path("drafts.**")))][0] {  _id, _type, _rev, _updatedAt, name, "slug": slug.current, role, bio, linkedin, twitter,  avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type AUTHOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "author";
  _rev: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  role: string | null;
  bio: string | null;
  linkedin: string | null;
  twitter: string | null;
  avatar: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: AUTHOR_POSTS_QUERY
// Query: *[  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && author->slug.current == $slug] | order(publishedAt desc, _id asc) {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  isFeatured, readingTime,  "category": categories[0]->{_id, title, "slug": slug.current},  "categories": categories[]->{_id, title, "slug": slug.current},  "author": author->{_id, name, "slug": slug.current, role, avatar{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type AUTHOR_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  isFeatured: boolean | null;
  readingTime: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: LABS_PROJECTS_QUERY
// Query: *[  _type == "labsProject" && ($preview || !(_id in path("drafts.**")))] | order(coalesce(displayOrder, 100) asc, startDate desc, _id asc) {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, status,  "partner": select(  partnerRef->isPublic == true => partnerRef->{    _id, name, url, logo{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}  },  null),  description, tags, startDate, endDate, publicationUrl, cta,  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}}
export type LABS_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "labsProject";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  status: "active" | "completed" | "upcoming" | null;
  partner: {
    _id: string;
    name: string | null;
    url: string | null;
    logo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  description: string | null;
  tags: Array<string> | null;
  startDate: string | null;
  endDate: string | null;
  publicationUrl: string | null;
  cta: Cta | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: LABS_PROJECT_BY_SLUG_QUERY
// Query: *[  _type == "labsProject" && slug.current == $slug && ($preview || !(_id in path("drafts.**")))] | order(_updatedAt desc)[0] {  _id, _type, _rev, _updatedAt, title, "slug": slug.current, status,  "partner": select(  partnerRef->isPublic == true => partnerRef->{    _id, name, url, logo{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}  },  null),  description, tags, startDate, endDate, publicationUrl, cta,  body[]{..., _type == "imageWithAlt" => {..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},  coverImage{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}},  "seo": {    "title": coalesce(seo.title, title),    "description": coalesce(seo.description, description),    "noIndex": coalesce(seo.noIndex, false),    "image": seo.image{  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}  }}
export type LABS_PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "labsProject";
  _rev: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  status: "active" | "completed" | "upcoming" | null;
  partner: {
    _id: string;
    name: string | null;
    url: string | null;
    logo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  description: string | null;
  tags: Array<string> | null;
  startDate: string | null;
  endDate: string | null;
  publicationUrl: string | null;
  cta: Cta | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "externalLink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
              lqip: null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
      }
  > | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          lqip: null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | false;
    image: {
      _type: "imageWithAlt";
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
            lqip: null;
          } | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
    } | null;
  };
} | null;

// Source: ../website/app/utils/sanity-queries.ts
// Variable: ACTIVE_ANNOUNCEMENT_QUERY
// Query: *[  _type == "announcement" && isActive == true && ($preview || !(_id in path("drafts.**")))] | order(_updatedAt desc, _id asc)[0] {  _id, _type, _rev, _updatedAt, text, tone,  "cta": coalesce(cta, {"label": linkText, "url": link, "style": "link"})}
export type ACTIVE_ANNOUNCEMENT_QUERY_RESULT = {
  _id: string;
  _type: "announcement";
  _rev: string;
  _updatedAt: string;
  text: string | null;
  tone: "info" | "success" | "warning" | null;
  cta:
    | Cta
    | {
        label: string | null;
        url: string | null;
        style: "link";
      };
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))] | order(publishedAt desc, _id asc) {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  isFeatured, readingTime,\n  "category": categories[0]->{_id, title, "slug": slug.current},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  "author": author->{_id, name, "slug": slug.current, role, avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}},\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': POSTS_QUERY_RESULT;
    '*[\n  _type == "category" && ($preview || !(_id in path("drafts.**"))) &&\n  count(*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && references(^._id)]) > 0\n] | order(title asc, _id asc) {\n  _id, title, "slug": slug.current\n}': BLOG_CATEGORIES_QUERY_RESULT;
    'count(*[_type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))])': BLOG_TOTAL_COUNT_QUERY_RESULT;
    '*[\n  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && "announcements" in categories[]->slug.current\n] | order(publishedAt desc, _id asc)[0] {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  isFeatured, readingTime,\n  "category": categories[0]->{_id, title, "slug": slug.current},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  "author": author->{_id, name, "slug": slug.current, role, avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}},\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': ANNOUNCEMENT_STORY_QUERY_RESULT;
    '*[\n  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && isFeatured == true\n] | order(publishedAt desc, _id asc)[0] {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  isFeatured, readingTime,\n  "category": categories[0]->{_id, title, "slug": slug.current},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  "author": author->{_id, name, "slug": slug.current, role, avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}},\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': FEATURED_POST_QUERY_RESULT;
    '*[\n  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && !(_id in $excludeIds) &&\n  ($category == "" || $category in categories[]->slug.current) &&\n  ($search == "" || lower(title) match $search || lower(excerpt) match $search)\n] | order(publishedAt desc, _id asc) [$start...$end] {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  isFeatured, readingTime,\n  "category": categories[0]->{_id, title, "slug": slug.current},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  "author": author->{_id, name, "slug": slug.current, role, avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}},\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': BLOG_POSTS_QUERY_RESULT;
    'count(*[\n  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && !(_id in $excludeIds) &&\n  ($category == "" || $category in categories[]->slug.current) &&\n  ($search == "" || lower(title) match $search || lower(excerpt) match $search)\n])': BLOG_POST_COUNT_QUERY_RESULT;
    '*[\n  _type == "post" && slug.current == $slug && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now()))\n] | order(_updatedAt desc)[0] {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  isFeatured, readingTime,\n  body[]{..., _type == "imageWithAlt" => {..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},\n  "seo": {\n    "title": coalesce(seo.title, seoTitle, title),\n    "description": coalesce(seo.description, seoDescription, excerpt),\n    "noIndex": coalesce(seo.noIndex, false),\n    "image": seo.image{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n  },\n  "category": categories[0]->{_id, title, "slug": slug.current},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  "author": author->{\n    _id, name, "slug": slug.current, role, bio, linkedin, twitter,\n    avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n  },\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': POST_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "author" && slug.current == $slug && ($preview || !(_id in path("drafts.**")))\n][0] {\n  _id, _type, _rev, _updatedAt, name, "slug": slug.current, role, bio, linkedin, twitter,\n  avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': AUTHOR_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "post" && defined(publishedAt) && ($preview || (!(_id in path("drafts.**")) && publishedAt <= now())) && author->slug.current == $slug\n] | order(publishedAt desc, _id asc) {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  isFeatured, readingTime,\n  "category": categories[0]->{_id, title, "slug": slug.current},\n  "categories": categories[]->{_id, title, "slug": slug.current},\n  "author": author->{_id, name, "slug": slug.current, role, avatar{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}},\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': AUTHOR_POSTS_QUERY_RESULT;
    '*[\n  _type == "labsProject" && ($preview || !(_id in path("drafts.**")))\n] | order(coalesce(displayOrder, 100) asc, startDate desc, _id asc) {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, status,\n  "partner": select(\n  partnerRef->isPublic == true => partnerRef->{\n    _id, name, url, logo{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n  },\n  null\n),\n  description, tags, startDate, endDate, publicationUrl, cta,\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n}': LABS_PROJECTS_QUERY_RESULT;
    '*[\n  _type == "labsProject" && slug.current == $slug && ($preview || !(_id in path("drafts.**")))\n] | order(_updatedAt desc)[0] {\n  _id, _type, _rev, _updatedAt, title, "slug": slug.current, status,\n  "partner": select(\n  partnerRef->isPublic == true => partnerRef->{\n    _id, name, url, logo{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n  },\n  null\n),\n  description, tags, startDate, endDate, publicationUrl, cta,\n  body[]{..., _type == "imageWithAlt" => {..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}}},\n  coverImage{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n},\n  "seo": {\n    "title": coalesce(seo.title, title),\n    "description": coalesce(seo.description, description),\n    "noIndex": coalesce(seo.noIndex, false),\n    "image": seo.image{\n  ..., asset->{_id, url, metadata{dimensions{width, height, aspectRatio, lqip}}}\n}\n  }\n}': LABS_PROJECT_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "announcement" && isActive == true && ($preview || !(_id in path("drafts.**")))\n] | order(_updatedAt desc, _id asc)[0] {\n  _id, _type, _rev, _updatedAt, text, tone,\n  "cta": coalesce(cta, {"label": linkText, "url": link, "style": "link"})\n}': ACTIVE_ANNOUNCEMENT_QUERY_RESULT;
  }
}
